"""empty message

Revision ID: dc8c8afddeb4
Revises: 42d5d115f1fc
Create Date: 2020-07-15 15:14:44.908184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8c8afddeb4'
down_revision = '42d5d115f1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('uri', sa.String(), nullable=False))
    op.drop_constraint('playlists_URI_key', 'playlists', type_='unique')
    op.create_unique_constraint(None, 'playlists', ['uri'])
    op.drop_column('playlists', 'URI')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('URI', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'playlists', type_='unique')
    op.create_unique_constraint('playlists_URI_key', 'playlists', ['URI'])
    op.drop_column('playlists', 'uri')
    # ### end Alembic commands ###
